### ISSUE TITLE
Can't find ./iterator.js error

### ISSUE THREAD

**Issue by jnaiman** [idyll-lang/idyll-vega-lite#16]
Error on both a Mac and a Windows when trying to use vega-lite:

![image](https://user-images.githubusercontent.com/26261800/140796558-8cd0834c-88d8-43c7-a4ef-1d5b12038ecc.png)

Thanks for any ideas!

**Comment by mathisonian** [comment]
Hi @jnaiman, sorry for the trouble. I am able to reproduce this locally. 

I think we should update this package to the latest versions of Vega & Vega-Lite and that may solve the issue (related: #14). Due to some work deadlines, I won't have time to get to this until January but would be happy to accept a PR before that or discuss a work around so that you can get visualizing in the meantime.

**Comment by jnaiman** [comment]
Hello @mathisonian, any ideas for a work-around would be great!  Right now I'm just going to teach with d3.js, but it would be nice to have for next semester.  I've tried a few different versions of vega/vega-lite but alas no luck yet.

**Comment by mathisonian** [comment]
@jnaiman this should be working now after the latest patch to `idyll`. Make sure install the latest version of both `idyll` and `idyll-vega-lite` in your project and things should build as expected using the latest vega/vega-lite versions.
